apiVersion: v1
kind: Pod
metadata:
  name: gm-<YOUR_NAME>
  labels:
    app: gm-<YOUR_NAME>
spec:
  containers:
  - name: gm-<YOUR_NAME>
    imagePullPolicy: Always
    image: systemsgenetics/gemmaker
    command: [ "/bin/sh" ]
    args: [ "-c", "COMMAND" ]
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 1
        memory: 4Gi
    volumeMounts:
    - name: gm-volume
      mountPath: /workspace
  restartPolicy: Always
  volumes:
    - name: gm-volume
      persistentVolumeClaim:
        claimName: task-pv-claim-<YOUR_NAME> # Enter valid PVC
