apiVersion: v1
kind: Pod
metadata:
  name: hicn-<YOUR_NAME>
  labels:
    app: hicn-<YOUR_NAME>
spec:
  containers:
  - name: hicn-<YOUR_NAME>
    imagePullPolicy: Always
    image: cbmckni/hicn-client
    command: [ "/bin/sh" ]
    args: [ "-c", "sleep infinity" ]
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN"]
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 1
        memory: 4Gi
    volumeMounts:
    - name: hicn-volume
      mountPath: /workspace
  restartPolicy: Always
  volumes:
    - name: hicn-volume
      persistentVolumeClaim:
        claimName: task-pv-claim-<YOUR_NAME> # Enter valid PVC
