apiVersion: v1
kind: Pod
metadata:
  name: kallisto-<YOUR_NAME>
  labels:
    app: kallisto-<YOUR_NAME>
spec:
  containers:
  - name: kallisto-<YOUR_NAME>
    imagePullPolicy: Always
    image: systemsgenetics/gemmaker
    command: [ "/bin/sh" ]
    args: [ "-c", "cd /workspace/gemmaker/ && kallisto index -i /workspace/gemmaker/Arabidopsis_thaliana.TAIR10.kallisto.indexed Arabidopsis_thaliana.TAIR10.cdna.all.fa.gz" ]
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 1
        memory: 4Gi
    volumeMounts:
    - name: gm-volume
      mountPath: /workspace
  restartPolicy: Always
  volumes:
    - name: gm-volume
      persistentVolumeClaim:
        claimName: pvc-<YOUR_NAME> # Enter valid PVC
