apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sra-batch-<YOUR_NAME>
  labels:
    app: sra-batch-<YOUR_NAME>
spec:
  serviceName: sra-batch-<YOUR_NAME>
  replicas: 7
  selector:
    matchLabels:
      app: sra-batch-<YOUR_NAME>
  template:
    metadata:
      labels:
        app: sra-batch-<YOUR_NAME>
    spec:
      containers:               
      - name: sra-batch-<YOUR_NAME>
        image: ncbi/sra-tools
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "cd /workspace/gemmaker && /workspace/gemmaker/pull_sample.sh /workspace/gemmaker/SRA_IDs.txt /workspace/gemmaker/input/" ]
        resources:
          requests:
            cpu: 1
            memory: 4Gi
          limits:
            cpu: 1
            memory: 4Gi
        volumeMounts:
        - name: sra-batch-pvc
          mountPath: /workspace
      restartPolicy: Always
      volumes:
        - name: sra-batch-pvc
          persistentVolumeClaim:
            claimName: pvc-<YOUR_NAME> # Enter valid PVC
